version: '2.1'
orbs:
  tfsec: mycodeself/tfsec@1.0.5
jobs:
  tf-iac-scan:
    executor: tfsec/default
    steps:
      - checkout
      - tfsec/scan:
          directory: .
          exclude-checks: 'GEN001,GCP001,GCP002'
workflows:
  analyze-tf-code:
    jobs:
      - tf-iac-scan